spring:
  datasource:
    username: root
    password: zzf233210
    url: jdbc:mysql://localhost:3306/movie_system?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #属性类型的字符串，通过别名的方式配置扩展插件， 监控统计用的stat 日志用log4j 防御sql注入:wall
    filters: stat
    #初始化时池中建立的物理连接个数。
    initialSize: 5
    #最大的可活跃的连接池数量
    maxActive: 300
    #获取连接时最大等待时间，单位毫秒，超过连接就会失效。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降， 如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    maxWait: 60000
    #连接回收器的运行周期时间，时间到了清理池中空闲的连接，testWhileIdle根据这个判断
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql，要求是一个查询语句。
    validationQuery: SELECT 1 FROM DUAL
    #建议配置为true，不影响性能，并且保证安全性。 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis， 执行validationQuery检测连接是否有效。
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。设置为false
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能,设置为flase
    testOnReturn: false
    #是否缓存preparedStatement，也就是PSCache。
    poolPreparedStatements: false
    #池中能够缓冲的preparedStatements语句数量
    maxPoolPreparedStatementPerConnectionSiz: =200

  jdbc:
    template:
      query-timeout: 3
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  mvc:
    static-path-pattern: /**



mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/testMapper.xml

logging:
  level:
    com.zzf.mapper: DEBUG

